[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "language_modeling"
version = "0.1.0"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["language_modeling"]